version: "3.9"

services:
  app:
    image: harbor.devops.com:8083/testproject/hello-docker:${APP_TAG}
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

