name: Develop workflow

on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run security scan
        run: echo "Running security scan..."
  build:
    runs-on: ubuntu-latest
    environment: development
    needs: [scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          docker build -t alfahimbin/my-app:latest .
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Docker push
        run: |
          docker push alfahimbin/my-app:latest
